// Generated by CoffeeScript 1.8.0
var plotChart, plotFacultyAverage, plotFacultyHighest;

plotChart = function(container, data, label_func, href_func, value_func, label, value) {
  var bars, chart, header;
  chart = d3.select(container);
  header = chart.append("li").attr("class", "header");
  header.append("a").text(label);
  header.append("label").text(value);
  bars = chart.selectAll("li.bar").data(data.values).enter().append("li").attr("class", "bar");
  bars.append("span").style("width", function(d) {
    return parseInt(d.value) / data.max * 100 + "%";
  }).append("a").attr("href", href_func).text(label_func);
  return bars.append("label").text(value_func);
};

plotFacultyGaps = function() {
  return d3.json("http://ubyssey.ca/wp-content/themes/theme/snippets/charts/salaries/gender/data/faculty_gaps.json", function(error, json) {
    return plotChart('.faculty-gaps', json, function(d) {
      return d.faculty;
    }, function(d) {
      return "http://ubyssey.ca/salaries/search/?faculty_id=" + d.url;
    }, function(d) {
      return d.value + "%";
    },
    'Faculty', 'Avg. female salary (% of male)');
  });
};

plotFacultyGaps();
